# Generated by Django 5.2.7 on 2025-10-31 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_alter_paymentcard_table_alter_transaction_table_and_more'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ride_matched', 'Ride Matched'), ('ride_accepted', 'Ride Accepted'), ('ride_started', 'Ride Started'), ('ride_completed', 'Ride Completed'), ('ride_cancelled', 'Ride Cancelled'), ('driver_arrived', 'Driver Arrived'), ('driver_nearby', 'Driver Nearby'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('wallet_credited', 'Wallet Credited'), ('wallet_debited', 'Wallet Debited'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('new_ride_request', 'New Ride Request'), ('rating_received', 'Rating Received'), ('driver_approved', 'Driver Account Approved'), ('promo_available', 'Promotion Available'), ('referral_bonus', 'Referral Bonus'), ('account_verified', 'Account Verified'), ('maintenance_alert', 'Maintenance Alert'), ('general', 'General')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data like ride_id, transaction_id, etc.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via_push', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rides.ride')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('html_body', models.TextField(blank=True, help_text='HTML version of the email', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'notifications_email_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_ride_updates', models.BooleanField(default=True, help_text='Receive push notifications for ride status updates')),
                ('push_payment_updates', models.BooleanField(default=True, help_text='Receive push notifications for payment updates')),
                ('push_promotional', models.BooleanField(default=True, help_text='Receive push notifications for promotions and offers')),
                ('push_enabled', models.BooleanField(default=True, help_text='Master switch for all push notifications')),
                ('sms_ride_updates', models.BooleanField(default=True, help_text='Receive SMS for critical ride updates')),
                ('sms_payment_updates', models.BooleanField(default=True, help_text='Receive SMS for payment confirmations')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Master switch for all SMS notifications')),
                ('email_ride_updates', models.BooleanField(default=True, help_text='Receive email receipts for completed rides')),
                ('email_payment_updates', models.BooleanField(default=True, help_text='Receive email for payment updates')),
                ('email_promotional', models.BooleanField(default=True, help_text='Receive promotional emails')),
                ('email_weekly_summary', models.BooleanField(default=True, help_text='Receive weekly activity summary email')),
                ('email_enabled', models.BooleanField(default=True, help_text='Master switch for all emails')),
                ('inapp_enabled', models.BooleanField(default=True, help_text='Show in-app notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours (no notifications during specified times)')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours (e.g., 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours (e.g., 07:00)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notifications_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='FCM device registration token', max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, help_text='Device model name (e.g., iPhone 13, Samsung Galaxy S21)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is still valid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time a notification was sent to this token')),
                ('user', models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'db_table': 'notifications_push_token',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(help_text='SMS provider used (africastalking, twilio, termii)', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from SMS provider', max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost in Naira or credits', max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='notifications.notification')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'db_table': 'notifications_sms_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email', 'status'], name='notificatio_recipie_543d65_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_19e574_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_ec5cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['token'], name='notificatio_token_213ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['phone_number', 'status'], name='notificatio_phone_n_b8ae6a_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_57e55b_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['provider'], name='notificatio_provide_1f8974_idx'),
        ),
    ]
