# Generated by Django 5.2.6 on 2025-10-21 11:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.CharField(choices=[('bike', 'Bike (Okada)'), ('keke', 'Keke (Tricycle)'), ('car', 'Car (Standard)'), ('suv', 'SUV (Premium)')], help_text='Unique identifier for vehicle type', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name', max_length=50)),
                ('description', models.TextField(help_text='Short description of vehicle type')),
                ('icon_name', models.CharField(default='directions_car', help_text='Material icon name for Flutter', max_length=50)),
                ('color', models.CharField(default='#0066FF', help_text='Hex color code for UI', max_length=7)),
                ('max_passengers', models.IntegerField(default=1)),
                ('has_luggage_space', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display in app (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is service available in this city?')),
                ('has_bike', models.BooleanField(default=True, help_text='Are bikes allowed in this city?')),
                ('has_keke', models.BooleanField(default=True, help_text='Are kekes allowed in this city?')),
                ('has_car', models.BooleanField(default=True, help_text='Are cars allowed in this city?')),
                ('has_suv', models.BooleanField(default=True, help_text='Are SUVs allowed in this city?')),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='vehicles_ci_name_cfa77f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_price_per_litre', models.DecimalField(decimal_places=2, help_text='Current fuel price per litre in Naira', max_digits=8)),
                ('baseline_fuel_price', models.DecimalField(decimal_places=2, default=Decimal('800.00'), help_text='Baseline fuel price (no adjustment below this)', max_digits=8)),
                ('adjustment_per_100_naira', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Add this amount per km for every ₦100 fuel increase', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_adjustments', to='vehicles.city')),
            ],
            options={
                'verbose_name_plural': 'Fuel price adjustments',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SurgePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Surge rule name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('surge_level', models.CharField(choices=[('normal', 'Normal (1.0x)'), ('light', 'Light Surge (1.2x)'), ('moderate', 'Moderate Surge (1.5x)'), ('heavy', 'Heavy Surge (2.0x)')], default='normal', max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Fare multiplier (1.0 = no surge, 2.0 = double fare)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('start_time', models.TimeField(blank=True, help_text='Start time for surge', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for surge', null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are applied first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text='Apply to specific city, or all cities if blank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surge_rules', to='vehicles.city')),
            ],
            options={
                'verbose_name_plural': 'Surge pricing rules',
                'ordering': ['-priority', '-multiplier'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='Base fare in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Price per kilometer in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_minute', models.DecimalField(decimal_places=2, help_text='Price per minute in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_fare', models.DecimalField(decimal_places=2, help_text='Minimum fare for this vehicle type', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_default', models.BooleanField(default=False, help_text='Use this pricing when city-specific pricing not found')),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_arrival_time', models.CharField(default='5 min', help_text='Estimated time for driver to arrive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text='Leave blank for default pricing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pricing', to='vehicles.city')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='vehicles.vehicletype')),
            ],
            options={
                'ordering': ['vehicle_type', 'city'],
                'indexes': [models.Index(fields=['vehicle_type', 'city', 'is_active'], name='vehicles_ve_vehicle_84f384_idx')],
                'unique_together': {('vehicle_type', 'city')},
            },
        ),
    ]
