# Generated by Django 5.2.6 on 2025-10-29 20:05

import django.core.validators
import django.db.models.deletion
import vehicles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Manufacturer: Toyota, Honda, TVS, etc.', max_length=50)),
                ('model', models.CharField(help_text='Model: Camry, Accord, Keke Napep, etc.', max_length=50)),
                ('year', models.IntegerField(help_text='Year of manufacture', validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)])),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(help_text='Vehicle license plate number', max_length=20, unique=True)),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=50, unique=True)),
                ('registration_expiry', models.DateField(help_text='Registration expiry date')),
                ('insurance_company', models.CharField(max_length=100)),
                ('insurance_policy_number', models.CharField(max_length=50, unique=True)),
                ('insurance_expiry', models.DateField()),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('next_inspection_due', models.DateField(blank=True, null=True)),
                ('inspection_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Vehicle is active and can be used')),
                ('is_verified', models.BooleanField(default=False, help_text='Vehicle documents verified by admin')),
                ('is_primary', models.BooleanField(default=False, help_text="Driver's primary vehicle for rides")),
                ('total_rides', models.IntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Driver who owns/operates this vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers.driver')),
                ('vehicle_type', models.ForeignKey(help_text='Category: bike, keke, car, suv', on_delete=django.db.models.deletion.PROTECT, related_name='registered_vehicles', to='pricing.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles_vehicle',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Vehicle Registration'), ('insurance', 'Insurance Certificate'), ('inspection', 'Inspection Report'), ('roadworthiness', 'Road Worthiness Certificate'), ('proof_of_ownership', 'Proof of Ownership')], max_length=50)),
                ('document', models.FileField(help_text='Upload document (PDF, JPG, PNG)', upload_to=vehicles.models.vehicle_document_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date (if applicable)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vehicle_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'db_table': 'vehicles_vehicle_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('front', 'Front View'), ('back', 'Back View'), ('left_side', 'Left Side'), ('right_side', 'Right Side'), ('interior', 'Interior'), ('dashboard', 'Dashboard'), ('license_plate', 'License Plate'), ('registration_doc', 'Registration Document Photo')], max_length=50)),
                ('image', models.ImageField(help_text='Vehicle photo (max 5MB)', upload_to=vehicles.models.vehicle_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
                'db_table': 'vehicles_vehicle_image',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspection_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Pass')], max_length=20)),
                ('brakes_ok', models.BooleanField(default=False)),
                ('lights_ok', models.BooleanField(default=False)),
                ('tires_ok', models.BooleanField(default=False)),
                ('engine_ok', models.BooleanField(default=False)),
                ('body_ok', models.BooleanField(default=False)),
                ('interior_ok', models.BooleanField(default=False)),
                ('mileage_km', models.IntegerField(blank=True, help_text='Vehicle mileage at inspection', null=True)),
                ('notes', models.TextField()),
                ('next_inspection_due', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Inspection',
                'verbose_name_plural': 'Vehicle Inspections',
                'db_table': 'vehicles_vehicle_inspection',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Repair'), ('tire_change', 'Tire Change'), ('oil_change', 'Oil Change'), ('brake_service', 'Brake Service'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, help_text='Maintenance cost in Naira', max_digits=10)),
                ('service_provider', models.CharField(help_text='Mechanic/Service center name', max_length=100)),
                ('maintenance_date', models.DateField()),
                ('mileage_km', models.IntegerField(blank=True, help_text='Vehicle mileage at maintenance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'db_table': 'vehicles_vehicle_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_active'], name='vehicles_ve_driver__0070f6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicles_ve_license_907c55_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_verified', 'is_active'], name='vehicles_ve_is_veri_40168f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicledocument',
            unique_together={('vehicle', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleimage',
            unique_together={('vehicle', 'image_type')},
        ),
    ]
