# Generated by Django 5.2.7 on 2025-10-31 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Setting identifier (e.g., 'base_fare')", max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', help_text='Type of value for validation', max_length=20)),
                ('description', models.TextField(blank=True, help_text='What this setting controls')),
                ('category', models.CharField(default='general', help_text='Setting category (pricing, features, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently in use')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('update', 'App Update'), ('promotion', 'Promotion'), ('announcement', 'General Announcement'), ('warning', 'Warning')], max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('riders', 'Riders Only'), ('drivers', 'Drivers Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send (blank = send immediately)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('harassment', 'Harassment'), ('unsafe_driving', 'Unsafe Driving'), ('fraud', 'Fraud'), ('inappropriate', 'Inappropriate Behavior'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ride')),
            ],
            options={
                'db_table': 'user_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_ban', 'Ban User'), ('user_unban', 'Unban User'), ('driver_approve', 'Approve Driver'), ('driver_reject', 'Reject Driver'), ('driver_suspend', 'Suspend Driver'), ('ride_cancel', 'Cancel Ride'), ('refund_issue', 'Issue Refund'), ('refund_reject', 'Reject Refund'), ('promo_create', 'Create Promo Code'), ('promo_disable', 'Disable Promo Code'), ('settings_update', 'Update Settings'), ('fare_adjust', 'Adjust Fare')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('target_type', models.CharField(help_text='Type of object affected (user, driver, ride, etc.)', max_length=50)),
                ('target_id', models.IntegerField(help_text='ID of the affected object')),
                ('reason', models.TextField(blank=True, help_text='Reason for this action')),
                ('metadata', models.JSONField(default=dict, help_text='Extra information about this action')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(help_text='Admin who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'db_table': 'admin_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='admin_actio_admin_i_85525e_idx'), models.Index(fields=['action_type', '-created_at'], name='admin_actio_action__123b9b_idx')],
            },
        ),
    ]
