# Generated by Django 5.2.6 on 2025-10-29 20:05

import django.core.validators
import django.db.models.deletion
import drivers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Driver License'), ('registration', 'Vehicle Registration'), ('insurance', 'Insurance Document'), ('id_card', 'National ID Card'), ('vehicle_inspection', 'Vehicle Inspection Certificate')], max_length=50)),
                ('document', models.FileField(upload_to=drivers.models.driver_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about document verification', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'db_table': 'drivers_verification_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('front', 'Front View'), ('back', 'Back View'), ('left_side', 'Left Side View'), ('right_side', 'Right Side View'), ('interior', 'Interior'), ('registration', 'Registration Plate'), ('dashboard', 'Dashboard')], max_length=50)),
                ('image', models.ImageField(help_text='Vehicle image (max 5MB)', upload_to=drivers.models.vehicle_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
                'db_table': 'drivers_vehicle_image',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('van', 'Van'), ('truck', 'Truck')], max_length=50)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(help_text='Vehicle license plate number (uppercase)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='License plate must contain only uppercase letters, numbers, and hyphens (3-15 chars)', regex='^[A-Z0-9-]{3,15}$')])),
                ('vehicle_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990, message='Vehicle year cannot be before 1990'), django.core.validators.MaxValueValidator(2026, message='Invalid vehicle year')])),
                ('driver_license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('driver_license_expiry', models.DateField()),
                ('background_check_passed', models.BooleanField(default=False)),
                ('background_check_date', models.DateTimeField(blank=True, null=True)),
                ('background_check_notes', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False, help_text='Whether driver is currently available for rides')),
                ('is_online', models.BooleanField(default=False, help_text='Whether driver is currently online')),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_rides', models.IntegerField(default=0)),
                ('completed_rides', models.IntegerField(default=0)),
                ('cancelled_rides', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_ratings', models.IntegerField(default=0, help_text='Total number of ratings received')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings in Naira', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drivers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'drivers_driver',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Driver Rating',
                'verbose_name_plural': 'Driver Ratings',
                'db_table': 'drivers_rating',
                'ordering': ['-created_at'],
            },
        ),
    ]
