# Generated by Django 5.2.6 on 2025-10-29 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrating',
            name='ride',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_rating', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='driverrating',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_driver_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driververificationdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driververificationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_images', to='drivers.driver'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['user', 'status'], name='drivers_dri_user_id_661581_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status', 'is_available'], name='drivers_dri_status_c6cd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_plate'], name='drivers_dri_license_9bdaab_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_license_number'], name='drivers_dri_driver__4f3818_idx'),
        ),
        migrations.AddIndex(
            model_name='driverrating',
            index=models.Index(fields=['driver', '-created_at'], name='drivers_rat_driver__6d97f1_idx'),
        ),
        migrations.AddIndex(
            model_name='driverrating',
            index=models.Index(fields=['rider', '-created_at'], name='drivers_rat_rider_i_b9e48a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driververificationdocument',
            unique_together={('driver', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleimage',
            unique_together={('driver', 'image_type')},
        ),
    ]
