# Generated by Django 5.2.6 on 2025-10-29 20:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.CharField(choices=[('bike', 'Bike (Okada)'), ('keke', 'Keke (Tricycle)'), ('car', 'Car (Standard)'), ('suv', 'SUV (Premium)')], help_text='Unique identifier for vehicle type', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='directions_car', help_text='Material icon name for Flutter', max_length=50)),
                ('color', models.CharField(default='#0066FF', help_text='Hex color code', max_length=7)),
                ('max_passengers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('has_luggage_space', models.BooleanField(default=False)),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Platform commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'db_table': 'vehicles_vehicle_type',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='City center latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='City center longitude', max_digits=11, null=True)),
                ('radius_km', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Service radius from city center in km', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Is service available in this city?')),
                ('has_bike', models.BooleanField(default=True)),
                ('has_keke', models.BooleanField(default=True)),
                ('has_car', models.BooleanField(default=True)),
                ('has_suv', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('minimum_driver_radius_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Search radius for nearby drivers', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'vehicles_city',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='vehicles_ci_name_cfa77f_idx'), models.Index(fields=['latitude', 'longitude'], name='vehicles_ci_latitud_12d730_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_price_per_litre', models.DecimalField(decimal_places=2, help_text='Current fuel price per litre in Naira', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('baseline_fuel_price', models.DecimalField(decimal_places=2, default=Decimal('800.00'), help_text='Baseline price (no adjustment below this)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('adjustment_per_100_naira', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Add per km for every ₦100 fuel increase', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_adjustments', to='pricing.city')),
            ],
            options={
                'verbose_name': 'Fuel Price Adjustment',
                'verbose_name_plural': 'Fuel Price Adjustments',
                'db_table': 'vehicles_fuel_price_adjustment',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['city', 'is_active', '-effective_date'], name='vehicles_fu_city_id_aed618_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurgePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('surge_level', models.CharField(choices=[('normal', 'Normal (1.0x)'), ('light', 'Light Surge (1.2x)'), ('moderate', 'Moderate Surge (1.5x)'), ('heavy', 'Heavy Surge (2.0x)'), ('extreme', 'Extreme Surge (3.0x)')], default='normal', max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Fare multiplier', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('start_time', models.TimeField(blank=True, help_text='Start time (leave blank for all day)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time (leave blank for all day)', null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules override lower ones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text='Specific city, or all cities if blank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surge_rules', to='pricing.city')),
            ],
            options={
                'verbose_name': 'Surge Pricing Rule',
                'verbose_name_plural': 'Surge Pricing Rules',
                'db_table': 'vehicles_surge_pricing',
                'ordering': ['-priority', '-multiplier'],
                'indexes': [models.Index(fields=['city', 'is_active', '-priority'], name='vehicles_su_city_id_ec8caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='Base fare in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Price per kilometer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_minute', models.DecimalField(decimal_places=2, help_text='Price per minute (for traffic)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_fare', models.DecimalField(decimal_places=2, help_text='Minimum fare', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_fare', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fare (optional cap)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for cancellation after driver accepts', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_arrival_time', models.CharField(default='5 min', help_text='Typical driver arrival time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text='Leave blank for default pricing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pricing', to='pricing.city')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='pricing.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle Pricing',
                'verbose_name_plural': 'Vehicle Pricing',
                'db_table': 'vehicles_vehicle_pricing',
                'ordering': ['vehicle_type', 'city'],
                'indexes': [models.Index(fields=['vehicle_type', 'city', 'is_active'], name='vehicles_ve_vehicle_ee86b0_idx'), models.Index(fields=['is_default', 'is_active'], name='vehicles_ve_is_defa_9e5006_idx')],
                'unique_together': {('vehicle_type', 'city')},
            },
        ),
    ]
