# Generated by Django 5.2.7 on 2025-11-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedlocation',
            options={'ordering': ['-updated_at']},
        ),
    ]
