# Generated by Django 5.2.7 on 2025-11-03 19:21

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('locations', '0002_alter_savedlocation_options'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverlocation',
            options={'verbose_name': 'Driver Location', 'verbose_name_plural': 'Driver Locations'},
        ),
        migrations.AlterModelOptions(
            name='ridetracking',
            options={'ordering': ['timestamp'], 'verbose_name': 'Ride Tracking Point', 'verbose_name_plural': 'Ride Tracking Points'},
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy radius in meters', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='bearing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Direction of travel in degrees (0-360)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Speed in kilometers per hour', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recentlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='recentlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AlterField(
            model_name='ridetracking',
            name='accuracy_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ridetracking',
            name='bearing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Direction of travel in degrees', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ridetracking',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='ridetracking',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AlterField(
            model_name='ridetracking',
            name='speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Speed at this point in km/h', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['driver', 'last_updated'], name='locations_d_driver__02de5b_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlocation',
            index=models.Index(fields=['user', '-last_used'], name='locations_r_user_id_74333f_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlocation',
            index=models.Index(fields=['-search_count'], name='locations_r_search__a7c6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ridetracking',
            index=models.Index(fields=['timestamp'], name='locations_r_timesta_1c6612_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlocation',
            index=models.Index(fields=['user', 'is_active'], name='locations_s_user_id_d1b5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlocation',
            index=models.Index(fields=['location_type'], name='locations_s_locatio_3cc25d_idx'),
        ),
        migrations.AlterModelTable(
            name='recentlocation',
            table='locations_recent_location',
        ),
        migrations.AlterModelTable(
            name='savedlocation',
            table='locations_saved_location',
        ),
    ]
