# Generated by Django 5.2.7 on 2025-10-31 21:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('unsafe_driving', 'Unsafe Driving'), ('harassment', 'Harassment'), ('route_deviation', 'Route Deviation'), ('vehicle_issue', 'Vehicle Issue'), ('accident', 'Accident'), ('threat', 'Threat/Violence'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(help_text='1=Minor, 5=Critical', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('evidence_images', models.JSONField(default=list, help_text='URLs to uploaded images')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('driver_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'db_table': 'safety_incident_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('response', models.CharField(choices=[('pending', 'Pending Response'), ('ok', 'User OK'), ('help', 'User Needs Help'), ('no_response', 'No Response')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('sos_triggered', models.BooleanField(default=False)),
                ('contacts_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Safety Check',
                'verbose_name_plural': 'Safety Checks',
                'db_table': 'safety_check',
                'ordering': ['check_time'],
            },
        ),
        migrations.CreateModel(
            name='SafetySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_share_trips', models.BooleanField(default=False, help_text='Share all rides automatically')),
                ('auto_safe_zone_notify', models.BooleanField(default=True, help_text='Notify when arriving at safe zone')),
                ('enable_safety_checks', models.BooleanField(default=True)),
                ('safety_check_interval', models.IntegerField(default=30, help_text='Minutes between checks')),
                ('quick_sos', models.BooleanField(default=True, help_text='Enable quick SOS button')),
                ('silent_sos', models.BooleanField(default=False, help_text='Trigger SOS without sound/vibration')),
                ('notify_contacts_on_ride_start', models.BooleanField(default=False)),
                ('notify_contacts_on_ride_end', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Settings',
                'verbose_name_plural': 'Safety Settings',
                'db_table': 'safety_settings',
            },
        ),
        migrations.CreateModel(
            name='SafeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('friend', 'Friend/Family'), ('other', 'Other')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius', models.IntegerField(default=100, help_text='Radius in meters')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('notify_on_arrival', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safe Zone',
                'verbose_name_plural': 'Safe Zones',
                'db_table': 'safety_safe_zone',
            },
        ),
        migrations.CreateModel(
            name='TripShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.JSONField(default=list, help_text="['+2348011111111', '+2348022222222']")),
                ('share_link', models.CharField(max_length=200, unique=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_code', models.CharField(blank=True, help_text='Optional PIN for tracking page', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_share', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Share',
                'verbose_name_plural': 'Trip Shares',
                'db_table': 'safety_trip_share',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact called first')),
                ('notify_sos', models.BooleanField(default=True)),
                ('notify_trip_share', models.BooleanField(default=True)),
                ('notify_trip_start', models.BooleanField(default=False)),
                ('notify_trip_end', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'db_table': 'safety_emergency_contact',
                'ordering': ['-is_primary', 'name'],
                'unique_together': {('user', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='EmergencySOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active - Help Needed!'), ('responding', 'Help On The Way'), ('resolved', 'Resolved - User Safe'), ('false_alarm', 'False Alarm')], db_index=True, default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional context from user')),
                ('contacts_notified', models.JSONField(default=list, help_text='Phone numbers that received alert')),
                ('admin_notified', models.BooleanField(default=False)),
                ('police_notified', models.BooleanField(default=False)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sos_alerts', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency SOS',
                'verbose_name_plural': 'Emergency SOS Alerts',
                'db_table': 'safety_emergency_sos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='safety_emer_user_id_5d9cc0_idx'), models.Index(fields=['status', '-created_at'], name='safety_emer_status_de0a24_idx')],
            },
        ),
    ]
