# Generated by Django 5.2.6 on 2025-10-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentcard',
            table='payments_payment_card',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='payments_transaction',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='payments_wallet',
        ),
        migrations.AlterModelTable(
            name='withdrawal',
            table='payments_withdrawal',
        ),
    ]
