# Generated by Django 5.2.6 on 2025-10-29 20:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('pricing', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_rides', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_hash', models.CharField(blank=True, max_length=32)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('fuel_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancellation_fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('destination_location', models.CharField(max_length=255)),
                ('destination_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('ride_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arriving', 'Driver Arriving'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('rider', 'Rider'), ('driver', 'Driver'), ('system', 'System')], max_length=10, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text="Rider's rating of the driver (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='pricing.city')),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this ride', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='drivers.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='vehicles.vehicle')),
                ('vehicle_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='pricing.vehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MutualRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_rating', models.IntegerField(blank=True, help_text="Rider's rating of driver (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rider_comment', models.TextField(blank=True, null=True)),
                ('rider_rated_at', models.DateTimeField(blank=True, null=True)),
                ('driver_rating', models.IntegerField(blank=True, help_text="Driver's rating of rider (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driver_comment', models.TextField(blank=True, null=True)),
                ('driver_rated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_rating', to='rides.ride')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Request expires if no driver accepts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_drivers', models.ManyToManyField(blank=True, help_text='Drivers who received this ride request', related_name='notified_rides', to='drivers.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.ride')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverRideResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('timeout', 'Timeout')], max_length=20)),
                ('decline_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_responses', to='drivers.driver')),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rides.riderequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['user', 'status'], name='rides_ride_user_id_aee52c_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_ride_driver__d3f652_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='rides_ride_status_9f4eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['status', 'expires_at'], name='rides_rider_status_26b763_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverrideresponse',
            unique_together={('ride_request', 'driver')},
        ),
    ]
