# Generated by Django 5.2.6 on 2025-10-20 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRideResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('timeout', 'Timeout')], max_length=20)),
                ('decline_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MutualRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_rating', models.IntegerField(blank=True, help_text="Rider's rating of driver (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rider_comment', models.TextField(blank=True, null=True)),
                ('rider_rated_at', models.DateTimeField(blank=True, null=True)),
                ('driver_rating', models.IntegerField(blank=True, help_text="Driver's rating of rider (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driver_comment', models.TextField(blank=True, null=True)),
                ('driver_rated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Request expires if no driver accepts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bearing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ride',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('rider', 'Rider'), ('driver', 'Driver'), ('system', 'System')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned to this ride', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='ride',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rating',
            field=models.IntegerField(blank=True, help_text="Rider's rating of the driver (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arriving', 'Driver Arriving'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['user', 'status'], name='rides_ride_user_id_aee52c_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_ride_driver__d3f652_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='rides_ride_status_9f4eb8_idx'),
        ),
        migrations.AddField(
            model_name='driverrideresponse',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_responses', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='mutualrating',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_rating', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='notified_drivers',
            field=models.ManyToManyField(blank=True, help_text='Drivers who received this ride request', related_name='notified_rides', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='driverrideresponse',
            name='ride_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rides.riderequest'),
        ),
        migrations.AddField(
            model_name='ridetracking',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='rides.ride'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['status', 'expires_at'], name='rides_rider_status_26b763_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverrideresponse',
            unique_together={('ride_request', 'driver')},
        ),
        migrations.AddIndex(
            model_name='ridetracking',
            index=models.Index(fields=['ride', 'timestamp'], name='rides_ridet_ride_id_d08746_idx'),
        ),
    ]
